# Generated by Django 4.2.2 on 2023-07-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='customer_country',
            field=models.CharField(default='', max_length=30),
        ),
    ]
