# Generated by Django 4.2.2 on 2023-06-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JammuAndKashmir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jammuandkashmir',
            name='Desc',
            field=models.TextField(default=''),
        ),
    ]
