# Generated by Django 4.2.2 on 2023-06-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JammuAndKashmir', '0002_jammuandkashmir_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jammuandkashmir',
            name='Desc',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
