# Generated by Django 4.2.2 on 2023-06-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JammuAndKashmir', '0003_alter_jammuandkashmir_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jammuandkashmir',
            name='Desc',
            field=models.TextField(default=''),
        ),
    ]
