# Generated by Django 4.2.2 on 2023-06-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JammuAndKashmir', '0004_alter_jammuandkashmir_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='jammuandkashmir',
            name='Visits_more_places',
            field=models.CharField(default='', max_length=90),
        ),
    ]
