# Generated by Django 4.2.2 on 2023-07-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JammuAndKashmir', '0006_gulmarg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anantnag',
            fields=[
                ('place_id', models.AutoField(primary_key=True, serialize=False)),
                ('Image', models.ImageField(default='', upload_to='JammuAndKashmir/images')),
                ('Place_name', models.CharField(max_length=70)),
                ('Sub_heading', models.CharField(default='', max_length=300)),
                ('Desc', models.TextField(default='')),
                ('Best_Time', models.CharField(default='', max_length=100)),
                ('Avoid_Time', models.CharField(default='', max_length=100)),
                ('Ideal_Duration', models.CharField(default='', max_length=50)),
                ('Category', models.CharField(default='', max_length=50)),
                ('More', models.TextField(default='')),
                ('Pub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pahalgam',
            fields=[
                ('place_id', models.AutoField(primary_key=True, serialize=False)),
                ('Image', models.ImageField(default='', upload_to='JammuAndKashmir/images')),
                ('Place_name', models.CharField(max_length=70)),
                ('Sub_heading', models.CharField(default='', max_length=300)),
                ('Desc', models.TextField(default='')),
                ('Best_Time', models.CharField(default='', max_length=100)),
                ('Avoid_Time', models.CharField(default='', max_length=100)),
                ('Ideal_Duration', models.CharField(default='', max_length=50)),
                ('Category', models.CharField(default='', max_length=50)),
                ('More', models.TextField(default='')),
                ('Pub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Srinagar',
            fields=[
                ('place_id', models.AutoField(primary_key=True, serialize=False)),
                ('Image', models.ImageField(default='', upload_to='JammuAndKashmir/images')),
                ('Place_name', models.CharField(max_length=70)),
                ('Sub_heading', models.CharField(default='', max_length=300)),
                ('Desc', models.TextField(default='')),
                ('Best_Time', models.CharField(default='', max_length=100)),
                ('Avoid_Time', models.CharField(default='', max_length=100)),
                ('Ideal_Duration', models.CharField(default='', max_length=50)),
                ('Category', models.CharField(default='', max_length=50)),
                ('More', models.TextField(default='')),
                ('Pub_date', models.DateField()),
            ],
        ),
    ]
