# Generated by Django 4.2.2 on 2023-07-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HimachalPradesh', '0002_manali'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manali',
            name='More',
            field=models.TextField(default=''),
        ),
    ]
