# Generated by Django 4.2.2 on 2023-07-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuideBooking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide_booking',
            name='Gender_identity',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='male', max_length=10, null=True),
        ),
    ]
